### ISSUE TITLE
What if you need to add gulp to your theme development setup?

### ISSUE THREAD

**Issue by mvaneijgen** [davidyeiser/docker-wordpress-theme-setup#1]
Great tutorial! I wish I had found this one earlier. I just spend the better part of my weekend setting up Docker with my Wordpress setup and sourced the internet for parts on how to set it up, yours seems so much more complete, so thanks! Now [here is what my `docker-compose.yml` file looks like](https://gist.github.com/mvaneijgen/7088fa56d91bd8a7d77f9629ea89e791), I also added phpMyAdmin for good measure.

Now here is where I am stuck, my Wordpress theme development runs on [Sage a theme developed by Roots.io](https://roots.io/sage/) and uses Gulp and Bower to compile static files. How would you add node, gulp and bower to your setup and run it from your theme folder inside the Docker container? I can easily run it from my host machine, but the best part of Docker is that you can run all your tools inside a confined container and run it with one command. 

Sorry to bother you and if this isn't the right place to ask just close this issue and I'll be on my way.

**Comment by davidyeiser** [comment]
You shouldn't have to do anything extra to Docker to run the Sage theme — Gulp/Bower will run independent of Docker. (I use Sage as well and run it all the time with a Docker setup.)

The main thing is you need to be able to access your `wp-content/themes` folder locally. Then you can just run `npm install` and `bower install` (if the latter is needed) in your Sage theme folder and that should install all the tools you need. Let me know if this doesn't make sense or if I'm missing something.

**Comment by mvaneijgen** [comment]
@davidyeiser thanks, but what if I do want to run Gulp and Bower in Docker. I am the most tech savvy person on my team and I just want to let my colleagues write CSS and JS in their favourite code editor and have them git commit there changes. I don't want to let them fiddle with getting Gulp te run correctly or if all the bower tools are installed. 

So the plan is create a full package in Docker have them run `docker-compose up` and setup a full dev environment which is mirrored on any PC it is installed on. 

I think I'm fairly far in with this concept https://github.com/mvaneijgen/docker-wordpress-with-gulp but I think I'm still missing a few pieces of the puzzle.

**Comment by davidyeiser** [comment]
Ah I see, I'm not sure to be honest. I would maybe try asking the Gulp community (e.g. https://github.com/gulpjs/gulp). Sorry I can't be of more help here.
