### ISSUE TITLE
[question] I got uploads.ini as a directory instead of a file

### ISSUE THREAD

**Issue by S-mardii** [davidyeiser/docker-wordpress-theme-setup#2]
I am a newbie to Docker, and I find your blog a good tutorial.

I added this, `./uploads:ini:/usr/local/etc/php/conf.d/uploads.ini`, to my `docker-compose.yml`. Then I get a directory named `uploads.ini` instead of a file named `uploads.ini`.

Please find the following screenshot of what I have got.
![image](https://user-images.githubusercontent.com/18528756/57120156-904e8680-6d99-11e9-830e-4462865038d1.png)

I am looking forward to hearing from you.
Cheers,

**Comment by czuli** [comment]
@S-mardii you have a mistake. You should write :
./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 

after word "upload" use dot not colon.

**Comment by davidyeiser** [comment]
@S-mardii First, apologies for the delayed reply — I didn’t receive notifications when new Issues were created.

The `uploads.ini` file needs to be created **before** you run `docker-compose up -d`. If you create the file first it will remain as a file. I’m not sure why it creates it as a directory, and there’s probably a better fix than “create the file first”, but that should fix your problem.

(Also, note the typo that @czuli pointed out)
