### ISSUE TITLE
Multiple versions

### ISSUE THREAD

**Issue by diversityX** [davidyeiser/docker-wordpress-theme-setup#3]
Thanks for the tutorial. It made this so simple.

How can I create multiple containers, with separate DB's and ports for the different sites? Do you have a tutorial for that?

**Comment by mario-neuhold** [comment]
Just create separate folders for each site in which you clone this repo and change the port in `docker-compose.yml` for each container. Then you can start each container from a terminal by typing `docker-compose up -d`.

**Comment by davidyeiser** [comment]
@mario-neuhold Thanks for answering this!

@diversityX Please re-open if you still have questions.

(Apologies for the delayed reply — I didn’t get notifications of new Issues)
