### ISSUE TITLE
[Question] Upload to a repo

### ISSUE THREAD

**Issue by luisgjb** [davidyeiser/docker-wordpress-theme-setup#5]
How should be handled in a repo? i mean after docker-compose is executed new files are created, should those files be added to .gitignore?

Thank you.

**Comment by luisgjb** [comment]
```
/wp-content/themes/twenty*
/wp-content/themes/index.php
/wp-content/plugins/akismet
/wp-content/plugins/hello.php
/wp-content/plugins/index.php
/wp-content/index.php
```
I added this to the main .gitignore

**Comment by davidyeiser** [comment]
Yep, that’s how you would do it. I essentially ignore everything except plugins (minus `hello.php` and `akismet`) and whatever theme I happen to be working on.

GitHub has a WordPress-specific .gitignore:
https://github.com/github/gitignore/blob/master/WordPress.gitignore

And WPEngine has one as well, though there’s is pretty verbose and would need to be updated to account for some of the later default theme releases:
https://wpengine.com/wp-content/uploads/2020/02/recommended-gitignore-no-wp.txt
